import { fetchSessionUser, fetchSessionUserMode } from "../utils/fetchSessionData";
import {IFoodItem, IInitialStateType} from "../../types";
import foodImg from "../img/r3.png";

const sessionUser = fetchSessionUser();
const sessionUserMode = fetchSessionUserMode();

const defaultItems: IFoodItem[] = [
    {
        id: 1,
        title: 'icecreams',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '15',
        category: 'icecreams',
    },
    {
        id: 2,
        title: 'fruits',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '25',
        category: 'fruits',
    },
    {
        id: 3,
        title: 'chicken',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '35',
        category: 'chicken',
    },
    {
        id: 4,
        title: 'desserts',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '45',
        category: 'desserts',
    },
    {
        id: 5,
        title: 'fish',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '55',
        category: 'fish',
    },
    {
        id: 6,
        title: 'rise',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '65',
        category: 'rise',
    },
    {
        id: 7,
        title: 'curry',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '75',
        category: 'curry',
    },
    {
        id: 8,
        title: 'fruit',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '85',
        category: 'fruit',
    },
    {
        id: 1123,
        title: 'icecreams',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '15',
        category: 'icecreams',
    },
    {
        id: 2123,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '25',
        category: 'fruits',
    },
    {
        id: 3123,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '35',
        category: 'chicken',
    },
    {
        id: 34,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '45',
        category: 'desserts',
    },
    {
        id: 54,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '55',
        category: 'fish',
    },
    {
        id: 623,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '65',
        category: 'rise',
    },
    {
        id: 723,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '75',
        category: 'curry',
    },
    {
        id: 83,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '85',
        category: 'fruit',
    },
    {
        id: 14,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '15',
        category: 'icecreams',
    },
    {
        id: 22,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '25',
        category: 'fruits',
    },
    {
        id: 334,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '35',
        category: 'chicken',
    },
    {
        id: 2344,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '45',
        category: 'desserts',
    },
    {
        id: 2345,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '55',
        category: 'fish',
    },
    {
        id: 62,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '65',
        category: 'rise',
    },
    {
        id: 723,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '75',
        category: 'curry',
    },
    {
        id: 38,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '85',
        category: 'fruit',
    },
    {
        id: 14,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '15',
        category: 'icecreams',
    },
    {
        id: 24,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '25',
        category: 'fruits',
    },
    {
        id: 33,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '35',
        category: 'chicken',
    },
    {
        id: 42,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '45',
        category: 'desserts',
    },
    {
        id: 53,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '55',
        category: 'fish',
    },
    {
        id: 63,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '65',
        category: 'rise',
    },
    {
        id: 73,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '75',
        category: 'curry',
    },
    {
        id: 48,
        title: 'Плов',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus blanditiis dolor dicta a, possimus omnis?',
        price: '10000 тг',
        imageURL: foodImg,
        calories: '100g',
        qty: '85',
        category: 'fruit',
    },
]
export const initialState: IInitialStateType = {
    user: sessionUser,
    foodItems: defaultItems,
    showCart: false,
    showContactForm: false,
    cartItems: [],
    cartTotal: 0,
    adminMode: sessionUserMode,
    users: [],
    paymentMethod: 'mobile_money',
    checkoutData: {},
}